[package]
name = "Tetri-rs"
version = "0.2.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["2d"]}
rand = "0.9.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
