[package]
name = "my_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
once_cell = "1.21.3"
palette = "0.7.6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
